- **EfficientNet**: https://github.com/lukemelas/EfficientNet-PyTorch

In [24]:
import torch.nn as nn

In [25]:
from efficientnet_pytorch import EfficientNet
model = EfficientNet.from_name('efficientnet-b0')

In [26]:
model

EfficientNet(
  (_conv_stem): Conv2dStaticSamePadding(
    3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False
    (static_padding): ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)
  )
  (_bn0): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
  (_blocks): ModuleList(
    (0): MBConvBlock(
      (_depthwise_conv): Conv2dStaticSamePadding(
        32, 32, kernel_size=(3, 3), stride=[1, 1], groups=32, bias=False
        (static_padding): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
      )
      (_bn1): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
      (_se_reduce): Conv2dStaticSamePadding(
        32, 8, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_se_expand): Conv2dStaticSamePadding(
        8, 32, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_project_conv): Conv2dStaticSamePadding(
        32, 16, kernel_size=

In [40]:
img = torch.randn(1, 3, 137, 236)
print(img.shape)

torch.Size([1, 3, 137, 236])


In [41]:
features = model.extract_features(img)
print(features.shape) 

torch.Size([1, 1280, 4, 7])


In [17]:
model._avg_pooling = nn.AdaptiveAvgPool2d(1)

In [18]:
model

EfficientNet(
  (_conv_stem): Conv2dStaticSamePadding(
    3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False
    (static_padding): ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)
  )
  (_bn0): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
  (_blocks): ModuleList(
    (0): MBConvBlock(
      (_depthwise_conv): Conv2dStaticSamePadding(
        32, 32, kernel_size=(3, 3), stride=[1, 1], groups=32, bias=False
        (static_padding): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
      )
      (_bn1): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
      (_se_reduce): Conv2dStaticSamePadding(
        32, 8, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_se_expand): Conv2dStaticSamePadding(
        8, 32, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_project_conv): Conv2dStaticSamePadding(
        32, 16, kernel_size=

In [20]:
model.ln = nn.LayerNorm(2580)

In [21]:
model

EfficientNet(
  (_conv_stem): Conv2dStaticSamePadding(
    3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False
    (static_padding): ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)
  )
  (_bn0): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
  (_blocks): ModuleList(
    (0): MBConvBlock(
      (_depthwise_conv): Conv2dStaticSamePadding(
        32, 32, kernel_size=(3, 3), stride=[1, 1], groups=32, bias=False
        (static_padding): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
      )
      (_bn1): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
      (_se_reduce): Conv2dStaticSamePadding(
        32, 8, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_se_expand): Conv2dStaticSamePadding(
        8, 32, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_project_conv): Conv2dStaticSamePadding(
        32, 16, kernel_size=

In [22]:
model.fc = nn.Linear(2580, 168*11*7)

In [23]:
model

EfficientNet(
  (_conv_stem): Conv2dStaticSamePadding(
    3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False
    (static_padding): ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)
  )
  (_bn0): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
  (_blocks): ModuleList(
    (0): MBConvBlock(
      (_depthwise_conv): Conv2dStaticSamePadding(
        32, 32, kernel_size=(3, 3), stride=[1, 1], groups=32, bias=False
        (static_padding): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
      )
      (_bn1): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
      (_se_reduce): Conv2dStaticSamePadding(
        32, 8, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_se_expand): Conv2dStaticSamePadding(
        8, 32, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_project_conv): Conv2dStaticSamePadding(
        32, 16, kernel_size=

In [20]:
model._fc.in_features

1280

In [21]:
model._dropouts = nn.ModuleList([
    nn.Dropout(0.5) for _ in range(5)
])

In [22]:
model

EfficientNet(
  (_conv_stem): Conv2dStaticSamePadding(
    3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False
    (static_padding): ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)
  )
  (_bn0): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
  (_blocks): ModuleList(
    (0): MBConvBlock(
      (_depthwise_conv): Conv2dStaticSamePadding(
        32, 32, kernel_size=(3, 3), stride=[1, 1], groups=32, bias=False
        (static_padding): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
      )
      (_bn1): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
      (_se_reduce): Conv2dStaticSamePadding(
        32, 8, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_se_expand): Conv2dStaticSamePadding(
        8, 32, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_project_conv): Conv2dStaticSamePadding(
        32, 16, kernel_size=

In [23]:
model._outer = nn.Linear(model._fc.in_features, 4096)

In [24]:
model

EfficientNet(
  (_conv_stem): Conv2dStaticSamePadding(
    3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False
    (static_padding): ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)
  )
  (_bn0): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
  (_blocks): ModuleList(
    (0): MBConvBlock(
      (_depthwise_conv): Conv2dStaticSamePadding(
        32, 32, kernel_size=(3, 3), stride=[1, 1], groups=32, bias=False
        (static_padding): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
      )
      (_bn1): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
      (_se_reduce): Conv2dStaticSamePadding(
        32, 8, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_se_expand): Conv2dStaticSamePadding(
        8, 32, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_project_conv): Conv2dStaticSamePadding(
        32, 16, kernel_size=

In [25]:
model._fc = nn.Identity()

In [26]:
model

EfficientNet(
  (_conv_stem): Conv2dStaticSamePadding(
    3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False
    (static_padding): ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)
  )
  (_bn0): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
  (_blocks): ModuleList(
    (0): MBConvBlock(
      (_depthwise_conv): Conv2dStaticSamePadding(
        32, 32, kernel_size=(3, 3), stride=[1, 1], groups=32, bias=False
        (static_padding): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
      )
      (_bn1): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
      (_se_reduce): Conv2dStaticSamePadding(
        32, 8, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_se_expand): Conv2dStaticSamePadding(
        8, 32, kernel_size=(1, 1), stride=(1, 1)
        (static_padding): Identity()
      )
      (_project_conv): Conv2dStaticSamePadding(
        32, 16, kernel_size=

In [16]:
import torch
import torch.nn.functional as F
from torch import nn

# define the network class
class MyNetwork(nn.Module):
    def __init__(self):
        # call constructor from superclass
        super().__init__()
        
        # define network layers
        self.fc1 = nn.Linear(16, 12)
        self.fc2 = nn.Linear(12, 10)
        self.fc3 = nn.Linear(10, 1)
        self.fc4 = nn.Linear(10, 5)
        
    def forward(self, x):
        # define forward pass
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

# instantiate the model
model = MyNetwork()

# print model architecture
print(model)

MyNetwork(
  (fc1): Linear(in_features=16, out_features=12, bias=True)
  (fc2): Linear(in_features=12, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
  (fc4): Linear(in_features=10, out_features=5, bias=True)
)


## Debugging

In [4]:
import torch 
import torch.nn as nn

class myNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3,10,2, stride = 2)
        self.relu = nn.ReLU()
        self.flatten = lambda x: x.view(-1)
        self.fc1 = nn.Linear(160,5)
        
    def forward(self, x):
        x = self.relu(self.conv(x))
        return self.fc1(self.flatten(x))


net = myNet()

In [5]:
net

myNet(
  (conv): Conv2d(3, 10, kernel_size=(2, 2), stride=(2, 2))
  (relu): ReLU()
  (fc1): Linear(in_features=160, out_features=5, bias=True)
)

In [ ]:
import torch

class MyLoss(torch.autograd.Function):
    def forward(self, x):
        import pdb
        pdb.set_trace()
        return x.view(-1).sum(0)
    def backward(self, x):
        import pdb
        pdb.set_trace()
        return x

v = torch.autograd.Variable(torch.randn(5, 5), requires_grad=True)
loss = MyLoss()(v)
loss.backward()

> <ipython-input-1-f479e08e1994>(7)forward()
-> return x.view(-1).sum(0)
(Pdb) l
  2  	
  3  	class MyLoss(torch.autograd.Function):
  4  	    def forward(self, x):
  5  	        import pdb
  6  	        pdb.set_trace()
  7  ->	        return x.view(-1).sum(0)
  8  	    def backward(self, x):
  9  	        import pdb
 10  	        pdb.set_trace()
 11  	        return x
 12  	
(Pdb) x
tensor([[-0.1586, -0.1918, -0.2016,  0.9976, -0.7192],
        [ 0.2888,  0.7962,  0.4305,  0.3788, -1.5952],
        [-0.1549, -1.4932,  1.4711, -0.1895, -1.4887],
        [ 0.0220,  0.7759, -2.0496,  1.0412, -1.2517],
        [-0.3335,  0.7478, -0.8807,  0.7978,  0.6146]], requires_grad=True)
(Pdb) v
tensor([[-0.1586, -0.1918, -0.2016,  0.9976, -0.7192],
        [ 0.2888,  0.7962,  0.4305,  0.3788, -1.5952],
        [-0.1549, -1.4932,  1.4711, -0.1895, -1.4887],
        [ 0.0220,  0.7759, -2.0496,  1.0412, -1.2517],
        [-0.3335,  0.7478, -0.8807,  0.7978,  0.6146]], requires_grad=True)
(Pdb) l
 13  

## Optimizer and Learning Rate
-To get below behavior, you should call it in every epoch, not only if the current epoch equals the step size.

In [6]:
import torch
import torch.optim as optim

In [9]:
optimizer = optim.SGD([torch.randn(1, requires_grad=True)], lr=1e-3)
exp_lr_scheduler = optim.lr_scheduler.StepLR(optimizer,
                                             step_size=7, gamma=0.1)

for epoch in range(1, 25):
    exp_lr_scheduler.step()
    print('Epoch {}, lr {}'.format(
        epoch, optimizer.param_groups[0]['lr']))

Epoch 1, lr 0.001
Epoch 2, lr 0.001
Epoch 3, lr 0.001
Epoch 4, lr 0.001
Epoch 5, lr 0.001
Epoch 6, lr 0.001
Epoch 7, lr 0.0001
Epoch 8, lr 0.0001
Epoch 9, lr 0.0001
Epoch 10, lr 0.0001
Epoch 11, lr 0.0001
Epoch 12, lr 0.0001
Epoch 13, lr 0.0001
Epoch 14, lr 1e-05
Epoch 15, lr 1e-05
Epoch 16, lr 1e-05
Epoch 17, lr 1e-05
Epoch 18, lr 1e-05
Epoch 19, lr 1e-05
Epoch 20, lr 1e-05
Epoch 21, lr 1.0000000000000002e-06
Epoch 22, lr 1.0000000000000002e-06
Epoch 23, lr 1.0000000000000002e-06
Epoch 24, lr 1.0000000000000002e-06


In [12]:
optimizer = optim.SGD([torch.randn(1, requires_grad=True)], lr=1e-3)
exp_lr_scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, 25)

for epoch in range(1, 25):
    exp_lr_scheduler.step()
    print('Epoch {}, lr {}'.format(
        epoch, optimizer.param_groups[0]['lr']))

Epoch 1, lr 0.000996057350657239
Epoch 2, lr 0.0009842915805643156
Epoch 3, lr 0.0009648882429441258
Epoch 4, lr 0.0009381533400219318
Epoch 5, lr 0.0009045084971874737
Epoch 6, lr 0.0008644843137107057
Epoch 7, lr 0.0008187119948743448
Epoch 8, lr 0.0007679133974894982
Epoch 9, lr 0.0007128896457825362
Epoch 10, lr 0.0006545084971874736
Epoch 11, lr 0.0005936906572928624
Epoch 12, lr 0.0005313952597646568
Epoch 13, lr 0.00046860474023534336
Epoch 14, lr 0.0004063093427071377
Epoch 15, lr 0.00034549150281252644
Epoch 16, lr 0.00028711035421746366
Epoch 17, lr 0.00023208660251050156
Epoch 18, lr 0.00018128800512565513
Epoch 19, lr 0.00013551568628929433
Epoch 20, lr 9.549150281252634e-05
Epoch 21, lr 6.184665997806823e-05
Epoch 22, lr 3.511175705587433e-05
Epoch 23, lr 1.570841943568452e-05
Epoch 24, lr 3.942649342761118e-06


In [15]:
optimizer = optim.SGD([torch.randn(1, requires_grad=True)], lr=1e-3)
exp_lr_scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, 25)

for epoch in range(1, 25):
    exp_lr_scheduler.step(epoch-1)
    print('Epoch {}, lr {}'.format(
        epoch, optimizer.param_groups[0]['lr']))

Epoch 1, lr 0.001
Epoch 2, lr 0.000996057350657239
Epoch 3, lr 0.0009842915805643156
Epoch 4, lr 0.0009648882429441257
Epoch 5, lr 0.0009381533400219318
Epoch 6, lr 0.0009045084971874737
Epoch 7, lr 0.0008644843137107057
Epoch 8, lr 0.0008187119948743449
Epoch 9, lr 0.0007679133974894983
Epoch 10, lr 0.0007128896457825364
Epoch 11, lr 0.0006545084971874737
Epoch 12, lr 0.0005936906572928624
Epoch 13, lr 0.0005313952597646568
Epoch 14, lr 0.0004686047402353433
Epoch 15, lr 0.0004063093427071377
Epoch 16, lr 0.00034549150281252644
Epoch 17, lr 0.00028711035421746366
Epoch 18, lr 0.00023208660251050156
Epoch 19, lr 0.00018128800512565513
Epoch 20, lr 0.00013551568628929433
Epoch 21, lr 9.549150281252633e-05
Epoch 22, lr 6.184665997806821e-05
Epoch 23, lr 3.5111757055874326e-05
Epoch 24, lr 1.5708419435684518e-05


## Torchvision Transforms

In [6]:
from torchvision import transforms
import torch
from torch.utils.data import Dataset

In [9]:
class experimental_dataset(Dataset):

    def __init__(self, data, transform):
        self.data = data
        self.transform = transform

    def __len__(self):
        return len(self.data.shape[0])

    def __getitem__(self, idx):
        item = self.data[idx]
        item = self.transform(item)
        return item

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor()
])

x = torch.rand(8, 1, 2, 2)
print(x)

dataset = experimental_dataset(x,transform)

for item in dataset:
    print(item)

tensor([[[[0.0416, 0.9765],
          [0.2405, 0.2627]]],


        [[[0.9799, 0.9438],
          [0.6130, 0.3069]]],


        [[[0.0294, 0.8320],
          [0.6896, 0.1558]]],


        [[[0.4167, 0.3665],
          [0.1559, 0.2764]]],


        [[[0.0849, 0.7227],
          [0.2045, 0.8976]]],


        [[[0.3275, 0.4737],
          [0.2426, 0.5756]]],


        [[[0.3555, 0.7436],
          [0.3043, 0.0666]]],


        [[[0.6182, 0.4931],
          [0.6381, 0.0819]]]])
tensor([[[0.0392, 0.9765],
         [0.2392, 0.2588]]])
tensor([[[0.9765, 0.9412],
         [0.6118, 0.3059]]])
tensor([[[0.8314, 0.0275],
         [0.1529, 0.6863]]])
tensor([[[0.4157, 0.3647],
         [0.1529, 0.2745]]])
tensor([[[0.0824, 0.7216],
         [0.2039, 0.8941]]])
tensor([[[0.4706, 0.3255],
         [0.5725, 0.2392]]])
tensor([[[0.3529, 0.7412],
         [0.3020, 0.0627]]])
tensor([[[0.6157, 0.4902],
         [0.6353, 0.0784]]])


## Layer Normalization (normalize across features)

In [38]:
import torch.nn as nn
from efficientnet_pytorch import EfficientNet

model = EfficientNet.from_name('efficientnet-b0')

In [42]:
x = torch.randn(50, 137, 236, 3)
print(x.size())
x = x.view(50, 3, 137, 236)
print(x.size())
x = model.extract_features(x)
print(x.size())

torch.Size([50, 137, 236, 3])
torch.Size([50, 3, 137, 236])
torch.Size([50, 1280, 4, 7])


In [43]:
x = nn.AdaptiveAvgPool2d(1)(x)
print(x.size())

torch.Size([50, 1280, 1, 1])


In [44]:
x = x.view(50, -1)
print(x.size())

torch.Size([50, 1280])


In [52]:
x = nn.LayerNorm(1280)(x)
print(x.size())

In [53]:
x = nn.Linear(1280, 14784)(x)
print(x.size())

# Data Loader

In [65]:
from torch.utils.data import DataLoader, Dataset
import torch

class MyDataset(Dataset):
    def __init__(self, size):
        self.x = torch.randn(size, 1)
    
    def __getitem__(self, index):
        return self.x[index]

    def __len__(self):
        return len(self.x)

dataset = MyDataset(1001)

data_loader = DataLoader(dataset,
                         batch_size=10)

print(len(dataset))
print(len(data_loader))

for batch_idx, data in enumerate(data_loader):
    print('batch idx{}, batch len {}'.format(
        batch_idx, len(data)))

data_loader = DataLoader(dataset,
                     batch_size=10,
                     drop_last=True)

print(len(data_loader))

for batch_idx, data in enumerate(data_loader):
    print('batch idx{}, batch len {}'.format(
        batch_idx, len(data)))

1001
101
batch idx0, batch len 10
batch idx1, batch len 10
batch idx2, batch len 10
batch idx3, batch len 10
batch idx4, batch len 10
batch idx5, batch len 10
batch idx6, batch len 10
batch idx7, batch len 10
batch idx8, batch len 10
batch idx9, batch len 10
batch idx10, batch len 10
batch idx11, batch len 10
batch idx12, batch len 10
batch idx13, batch len 10
batch idx14, batch len 10
batch idx15, batch len 10
batch idx16, batch len 10
batch idx17, batch len 10
batch idx18, batch len 10
batch idx19, batch len 10
batch idx20, batch len 10
batch idx21, batch len 10
batch idx22, batch len 10
batch idx23, batch len 10
batch idx24, batch len 10
batch idx25, batch len 10
batch idx26, batch len 10
batch idx27, batch len 10
batch idx28, batch len 10
batch idx29, batch len 10
batch idx30, batch len 10
batch idx31, batch len 10
batch idx32, batch len 10
batch idx33, batch len 10
batch idx34, batch len 10
batch idx35, batch len 10
batch idx36, batch len 10
batch idx37, batch len 10
batch idx38, 

In [69]:
from torch.utils.data import DataLoader, Dataset
import torch

class MyDataset(Dataset):
    def __init__(self, size):
        self.x = torch.randn(size, 1)
    
    def __getitem__(self, index):
        return self.x[index]

    def __len__(self):
        return len(self.x)

epochs = 40
dataset = MyDataset(1001)

data_sampler = torch.utils.data.RandomSampler(dataset, 
                                              replacement=True, 
                                              num_samples=len(dataset)*epochs)

data_loader = DataLoader(dataset,
                         batch_size=10,
                         drop_last=True,
                         sampler=data_sampler)

print(len(dataset))
print(len(data_loader))
print(len(data_sampler))

for batch_idx, data in enumerate(data_loader):
    print('batch idx{}, batch len {}'.format(
        batch_idx, len(data)))

1001
4004
40040
batch idx0, batch len 10
batch idx1, batch len 10
batch idx2, batch len 10
batch idx3, batch len 10
batch idx4, batch len 10
batch idx5, batch len 10
batch idx6, batch len 10
batch idx7, batch len 10
batch idx8, batch len 10
batch idx9, batch len 10
batch idx10, batch len 10
batch idx11, batch len 10
batch idx12, batch len 10
batch idx13, batch len 10
batch idx14, batch len 10
batch idx15, batch len 10
batch idx16, batch len 10
batch idx17, batch len 10
batch idx18, batch len 10
batch idx19, batch len 10
batch idx20, batch len 10
batch idx21, batch len 10
batch idx22, batch len 10
batch idx23, batch len 10
batch idx24, batch len 10
batch idx25, batch len 10
batch idx26, batch len 10
batch idx27, batch len 10
batch idx28, batch len 10
batch idx29, batch len 10
batch idx30, batch len 10
batch idx31, batch len 10
batch idx32, batch len 10
batch idx33, batch len 10
batch idx34, batch len 10
batch idx35, batch len 10
batch idx36, batch len 10
batch idx37, batch len 10
batch 

batch idx306, batch len 10
batch idx307, batch len 10
batch idx308, batch len 10
batch idx309, batch len 10
batch idx310, batch len 10
batch idx311, batch len 10
batch idx312, batch len 10
batch idx313, batch len 10
batch idx314, batch len 10
batch idx315, batch len 10
batch idx316, batch len 10
batch idx317, batch len 10
batch idx318, batch len 10
batch idx319, batch len 10
batch idx320, batch len 10
batch idx321, batch len 10
batch idx322, batch len 10
batch idx323, batch len 10
batch idx324, batch len 10
batch idx325, batch len 10
batch idx326, batch len 10
batch idx327, batch len 10
batch idx328, batch len 10
batch idx329, batch len 10
batch idx330, batch len 10
batch idx331, batch len 10
batch idx332, batch len 10
batch idx333, batch len 10
batch idx334, batch len 10
batch idx335, batch len 10
batch idx336, batch len 10
batch idx337, batch len 10
batch idx338, batch len 10
batch idx339, batch len 10
batch idx340, batch len 10
batch idx341, batch len 10
batch idx342, batch len 10
b

batch idx609, batch len 10
batch idx610, batch len 10
batch idx611, batch len 10
batch idx612, batch len 10
batch idx613, batch len 10
batch idx614, batch len 10
batch idx615, batch len 10
batch idx616, batch len 10
batch idx617, batch len 10
batch idx618, batch len 10
batch idx619, batch len 10
batch idx620, batch len 10
batch idx621, batch len 10
batch idx622, batch len 10
batch idx623, batch len 10
batch idx624, batch len 10
batch idx625, batch len 10
batch idx626, batch len 10
batch idx627, batch len 10
batch idx628, batch len 10
batch idx629, batch len 10
batch idx630, batch len 10
batch idx631, batch len 10
batch idx632, batch len 10
batch idx633, batch len 10
batch idx634, batch len 10
batch idx635, batch len 10
batch idx636, batch len 10
batch idx637, batch len 10
batch idx638, batch len 10
batch idx639, batch len 10
batch idx640, batch len 10
batch idx641, batch len 10
batch idx642, batch len 10
batch idx643, batch len 10
batch idx644, batch len 10
batch idx645, batch len 10
b

batch idx912, batch len 10
batch idx913, batch len 10
batch idx914, batch len 10
batch idx915, batch len 10
batch idx916, batch len 10
batch idx917, batch len 10
batch idx918, batch len 10
batch idx919, batch len 10
batch idx920, batch len 10
batch idx921, batch len 10
batch idx922, batch len 10
batch idx923, batch len 10
batch idx924, batch len 10
batch idx925, batch len 10
batch idx926, batch len 10
batch idx927, batch len 10
batch idx928, batch len 10
batch idx929, batch len 10
batch idx930, batch len 10
batch idx931, batch len 10
batch idx932, batch len 10
batch idx933, batch len 10
batch idx934, batch len 10
batch idx935, batch len 10
batch idx936, batch len 10
batch idx937, batch len 10
batch idx938, batch len 10
batch idx939, batch len 10
batch idx940, batch len 10
batch idx941, batch len 10
batch idx942, batch len 10
batch idx943, batch len 10
batch idx944, batch len 10
batch idx945, batch len 10
batch idx946, batch len 10
batch idx947, batch len 10
batch idx948, batch len 10
b

batch idx1207, batch len 10
batch idx1208, batch len 10
batch idx1209, batch len 10
batch idx1210, batch len 10
batch idx1211, batch len 10
batch idx1212, batch len 10
batch idx1213, batch len 10
batch idx1214, batch len 10
batch idx1215, batch len 10
batch idx1216, batch len 10
batch idx1217, batch len 10
batch idx1218, batch len 10
batch idx1219, batch len 10
batch idx1220, batch len 10
batch idx1221, batch len 10
batch idx1222, batch len 10
batch idx1223, batch len 10
batch idx1224, batch len 10
batch idx1225, batch len 10
batch idx1226, batch len 10
batch idx1227, batch len 10
batch idx1228, batch len 10
batch idx1229, batch len 10
batch idx1230, batch len 10
batch idx1231, batch len 10
batch idx1232, batch len 10
batch idx1233, batch len 10
batch idx1234, batch len 10
batch idx1235, batch len 10
batch idx1236, batch len 10
batch idx1237, batch len 10
batch idx1238, batch len 10
batch idx1239, batch len 10
batch idx1240, batch len 10
batch idx1241, batch len 10
batch idx1242, batch

batch idx1499, batch len 10
batch idx1500, batch len 10
batch idx1501, batch len 10
batch idx1502, batch len 10
batch idx1503, batch len 10
batch idx1504, batch len 10
batch idx1505, batch len 10
batch idx1506, batch len 10
batch idx1507, batch len 10
batch idx1508, batch len 10
batch idx1509, batch len 10
batch idx1510, batch len 10
batch idx1511, batch len 10
batch idx1512, batch len 10
batch idx1513, batch len 10
batch idx1514, batch len 10
batch idx1515, batch len 10
batch idx1516, batch len 10
batch idx1517, batch len 10
batch idx1518, batch len 10
batch idx1519, batch len 10
batch idx1520, batch len 10
batch idx1521, batch len 10
batch idx1522, batch len 10
batch idx1523, batch len 10
batch idx1524, batch len 10
batch idx1525, batch len 10
batch idx1526, batch len 10
batch idx1527, batch len 10
batch idx1528, batch len 10
batch idx1529, batch len 10
batch idx1530, batch len 10
batch idx1531, batch len 10
batch idx1532, batch len 10
batch idx1533, batch len 10
batch idx1534, batch

batch idx1791, batch len 10
batch idx1792, batch len 10
batch idx1793, batch len 10
batch idx1794, batch len 10
batch idx1795, batch len 10
batch idx1796, batch len 10
batch idx1797, batch len 10
batch idx1798, batch len 10
batch idx1799, batch len 10
batch idx1800, batch len 10
batch idx1801, batch len 10
batch idx1802, batch len 10
batch idx1803, batch len 10
batch idx1804, batch len 10
batch idx1805, batch len 10
batch idx1806, batch len 10
batch idx1807, batch len 10
batch idx1808, batch len 10
batch idx1809, batch len 10
batch idx1810, batch len 10
batch idx1811, batch len 10
batch idx1812, batch len 10
batch idx1813, batch len 10
batch idx1814, batch len 10
batch idx1815, batch len 10
batch idx1816, batch len 10
batch idx1817, batch len 10
batch idx1818, batch len 10
batch idx1819, batch len 10
batch idx1820, batch len 10
batch idx1821, batch len 10
batch idx1822, batch len 10
batch idx1823, batch len 10
batch idx1824, batch len 10
batch idx1825, batch len 10
batch idx1826, batch

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)




batch idx2508, batch len 10
batch idx2509, batch len 10
batch idx2510, batch len 10
batch idx2511, batch len 10
batch idx2512, batch len 10
batch idx2513, batch len 10
batch idx2514, batch len 10
batch idx2515, batch len 10
batch idx2516, batch len 10
batch idx2517, batch len 10
batch idx2518, batch len 10
batch idx2519, batch len 10
batch idx2520, batch len 10
batch idx2521, batch len 10
batch idx2522, batch len 10
batch idx2523, batch len 10
batch idx2524, batch len 10
batch idx2525, batch len 10
batch idx2526, batch len 10
batch idx2527, batch len 10
batch idx2528, batch len 10
batch idx2529, batch len 10
batch idx2530, batch len 10
batch idx2531, batch len 10
batch idx2532, batch len 10
batch idx2533, batch len 10
batch idx2534, batch len 10
batch idx2535, batch len 10
batch idx2536, batch len 10
batch idx2537, batch len 10
batch idx2538, batch len 10
batch idx2539, batch len 10
batch idx2540, batch len 10
batch idx2541, batch len 10
batch idx2542, batch len 10
batch idx2543, batc

batch idx2800, batch len 10
batch idx2801, batch len 10
batch idx2802, batch len 10
batch idx2803, batch len 10
batch idx2804, batch len 10
batch idx2805, batch len 10
batch idx2806, batch len 10
batch idx2807, batch len 10
batch idx2808, batch len 10
batch idx2809, batch len 10
batch idx2810, batch len 10
batch idx2811, batch len 10
batch idx2812, batch len 10
batch idx2813, batch len 10
batch idx2814, batch len 10
batch idx2815, batch len 10
batch idx2816, batch len 10
batch idx2817, batch len 10
batch idx2818, batch len 10
batch idx2819, batch len 10
batch idx2820, batch len 10
batch idx2821, batch len 10
batch idx2822, batch len 10
batch idx2823, batch len 10
batch idx2824, batch len 10
batch idx2825, batch len 10
batch idx2826, batch len 10
batch idx2827, batch len 10
batch idx2828, batch len 10
batch idx2829, batch len 10
batch idx2830, batch len 10
batch idx2831, batch len 10
batch idx2832, batch len 10
batch idx2833, batch len 10
batch idx2834, batch len 10
batch idx2835, batch

batch idx3092, batch len 10
batch idx3093, batch len 10
batch idx3094, batch len 10
batch idx3095, batch len 10
batch idx3096, batch len 10
batch idx3097, batch len 10
batch idx3098, batch len 10
batch idx3099, batch len 10
batch idx3100, batch len 10
batch idx3101, batch len 10
batch idx3102, batch len 10
batch idx3103, batch len 10
batch idx3104, batch len 10
batch idx3105, batch len 10
batch idx3106, batch len 10
batch idx3107, batch len 10
batch idx3108, batch len 10
batch idx3109, batch len 10
batch idx3110, batch len 10
batch idx3111, batch len 10
batch idx3112, batch len 10
batch idx3113, batch len 10
batch idx3114, batch len 10
batch idx3115, batch len 10
batch idx3116, batch len 10
batch idx3117, batch len 10
batch idx3118, batch len 10
batch idx3119, batch len 10
batch idx3120, batch len 10
batch idx3121, batch len 10
batch idx3122, batch len 10
batch idx3123, batch len 10
batch idx3124, batch len 10
batch idx3125, batch len 10
batch idx3126, batch len 10
batch idx3127, batch

batch idx3384, batch len 10
batch idx3385, batch len 10
batch idx3386, batch len 10
batch idx3387, batch len 10
batch idx3388, batch len 10
batch idx3389, batch len 10
batch idx3390, batch len 10
batch idx3391, batch len 10
batch idx3392, batch len 10
batch idx3393, batch len 10
batch idx3394, batch len 10
batch idx3395, batch len 10
batch idx3396, batch len 10
batch idx3397, batch len 10
batch idx3398, batch len 10
batch idx3399, batch len 10
batch idx3400, batch len 10
batch idx3401, batch len 10
batch idx3402, batch len 10
batch idx3403, batch len 10
batch idx3404, batch len 10
batch idx3405, batch len 10
batch idx3406, batch len 10
batch idx3407, batch len 10
batch idx3408, batch len 10
batch idx3409, batch len 10
batch idx3410, batch len 10
batch idx3411, batch len 10
batch idx3412, batch len 10
batch idx3413, batch len 10
batch idx3414, batch len 10
batch idx3415, batch len 10
batch idx3416, batch len 10
batch idx3417, batch len 10
batch idx3418, batch len 10
batch idx3419, batch

batch idx3676, batch len 10
batch idx3677, batch len 10
batch idx3678, batch len 10
batch idx3679, batch len 10
batch idx3680, batch len 10
batch idx3681, batch len 10
batch idx3682, batch len 10
batch idx3683, batch len 10
batch idx3684, batch len 10
batch idx3685, batch len 10
batch idx3686, batch len 10
batch idx3687, batch len 10
batch idx3688, batch len 10
batch idx3689, batch len 10
batch idx3690, batch len 10
batch idx3691, batch len 10
batch idx3692, batch len 10
batch idx3693, batch len 10
batch idx3694, batch len 10
batch idx3695, batch len 10
batch idx3696, batch len 10
batch idx3697, batch len 10
batch idx3698, batch len 10
batch idx3699, batch len 10
batch idx3700, batch len 10
batch idx3701, batch len 10
batch idx3702, batch len 10
batch idx3703, batch len 10
batch idx3704, batch len 10
batch idx3705, batch len 10
batch idx3706, batch len 10
batch idx3707, batch len 10
batch idx3708, batch len 10
batch idx3709, batch len 10
batch idx3710, batch len 10
batch idx3711, batch

batch idx3968, batch len 10
batch idx3969, batch len 10
batch idx3970, batch len 10
batch idx3971, batch len 10
batch idx3972, batch len 10
batch idx3973, batch len 10
batch idx3974, batch len 10
batch idx3975, batch len 10
batch idx3976, batch len 10
batch idx3977, batch len 10
batch idx3978, batch len 10
batch idx3979, batch len 10
batch idx3980, batch len 10
batch idx3981, batch len 10
batch idx3982, batch len 10
batch idx3983, batch len 10
batch idx3984, batch len 10
batch idx3985, batch len 10
batch idx3986, batch len 10
batch idx3987, batch len 10
batch idx3988, batch len 10
batch idx3989, batch len 10
batch idx3990, batch len 10
batch idx3991, batch len 10
batch idx3992, batch len 10
batch idx3993, batch len 10
batch idx3994, batch len 10
batch idx3995, batch len 10
batch idx3996, batch len 10

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

